---
- hosts: all
  become: true
  tasks:

    - name: Install Docker
      when: ansible_distribution == 'CentOS'
      dnf:
        name: docker-ce
        state: present

    - name: Install Docker
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: docker.io
        state: present

    - name: Enable Docker socket
      systemd:
        name: docker.socket
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create Dockerfile
      copy:
        content: |
          FROM ubuntu:latest

          RUN apt-get update && \
              apt-get install -y apache2 mysql-server

          EXPOSE 80 3306

          CMD ["apache2ctl", "-D", "FOREGROUND"]
        dest: /home/{{ ansible_user }}/Dockerfile
      when: ansible_distribution == 'Ubuntu'

    - name: Create Dockerfile
      copy:
        content: |
          FROM centos:latest

          RUN yum update -y && \
              yum install -y httpd mariadb-server

          EXPOSE 80 3306

          CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
        dest: /home/{{ ansible_user }}/Dockerfile
      when: ansible_distribution == 'CentOS'

    - name: Install and build Dockerfile using Ansible
      docker_image:
        path: /home/{{ ansible_user }}/Dockerfile
        name: myimage
        source: build
